import { CheckCircle2, Clock, AlertCircle } from "lucide-react";

export const MOCK_DATA = [
  {
    id: 1,
    contractArea: "Technology Services",
    businessArea: "IT Department",
    title: "Cloud Infrastructure Agreement",
    type: "Service Agreement",
    value: 245000,
    counterparty: "AWS Enterprise",
    status: "active",
    startDate: "2024-01-15",
    endDate: "2025-01-14",
    owner: "John Smith",
    legalEntity: "ABC Corp",
    duration: "12 Months",
    recordNumber: "CTR-001",
  },
  {
    id: 2,
    contractArea: "Sales & Marketing",
    businessArea: "Marketing Division",
    title: "Digital Marketing Services",
    type: "Consulting Agreement",
    value: 125000,
    counterparty: "MediaTech Solutions",
    status: "active",
    startDate: "2024-02-01",
    endDate: "2024-12-31",
    owner: "Optimus BT",
    legalEntity: "XYZ Corp",
    duration: "14 Months",
    recordNumber: "RTR-001",
  },
  {
    id: 3,
    contractArea: "Operations",
    businessArea: "Facilities Management",
    title: "Office Lease Agreement",
    type: "Real Estate",
    value: 480000,
    counterparty: "Metro Properties Inc",
    status: "active",
    startDate: "2023-06-01",
    endDate: "2026-05-31",
    owner: "Dwayne Smith",
    legalEntity: "ABCDE",
    duration: "8 Months",
    recordNumber: "vtR-001",
  },
  {
    id: 4,
    contractArea: "Human Resources",
    businessArea: "HR Department",
    title: "Recruitment Services Contract",
    type: "Service Agreement",
    value: 89000,
    counterparty: "TalentFinder Pro",
    status: "pending",
    startDate: "2024-03-15",
    endDate: "2024-09-14",
    owner: "John Cena",
    legalEntity: "ABCDE Corp",
    duration: "19 Months",
    recordNumber: "YTR-896",
  },
  {
    id: 5,
    contractArea: "Legal & Compliance",
    businessArea: "Legal Department",
    title: "Legal Advisory Retainer",
    type: "Professional Services",
    value: 340000,
    counterparty: "Sterling Law Group",
    status: "active",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    owner: "John Doe",
    legalEntity: "ETC Corp",
    duration: "5 Months",
    recordNumber: "JTR-001",
  },
];

export const FILTER_FIELDS = [
  "Business Area",
  "Contract Type",
  "Legal Entity",
  "Term Type",
  "Status",
  "Approver(s)",
  "Reviewer(s)",
  "Internal Signee(s)",
  "Start Date",
  "Created Date",
  "Last Modified Date",
  "Last Signed Date",
  "Project Name",
  "Duration",
  "Labels",
  "Contract Owner(s)",
  "Business Owner(s)",
];

export const ALL_COLUMNS = [
  { key: "contractArea", label: "Contract Area" },
  { key: "businessArea", label: "Business Area" },
  { key: "recordNumber", label: "Contract Record Number" },
  { key: "title", label: "Contract Record Title" },
  { key: "type", label: "Contract Record Type" },
  { key: "value", label: "Contract Value" },
  { key: "counterparty", label: "Counterparty Name(s)" },
  { key: "status", label: "Status" },

  // ✅ NEW DEMO COLUMNS
  { key: "owner", label: "Contract Owner" },
  { key: "legalEntity", label: "Legal Entity" },
  { key: "duration", label: "Duration" },
];

export const STATUS_CONFIG = {
  active: {
    label: "Active",
    icon: <CheckCircle2 className="w-3.5 h-3.5" />,
    className: "bg-emerald-100 text-emerald-700 border-emerald-200",
  },
  pending: {
    label: "Pending",
    icon: <Clock className="w-3.5 h-3.5" />,
    className: "bg-amber-100 text-amber-700 border-amber-200",
  },
  expired: {
    label: "Expired",
    icon: <AlertCircle className="w-3.5 h-3.5" />,
    className: "bg-red-100 text-red-700 border-red-200",
  },
};

export const REPORT_NAMES: { [key: string]: string } = {
  active: "Active Contracts",
  recent: "Recently Signed",
  cancelled: "Cancelled & Expired",
  abandoned: "Abandoned Contracts",
  draft: "Draft Contracts",
  upcoming: "Upcoming Renewals",
  history: "Renewal History",
};

export const CATEGORY_NAMES: { [key: string]: string } = {
  "contract-status": "Contract Status",
  renewals: "Renewals & Expirations",
  workflow: "Workflow Analytics",
  access: "Security & Access",
};
